### ISSUE TITLE
Compilation error (Module HelloPhoenix.Web is not loaded)

### ISSUE THREAD

**Issue by AndrewHendrie** [vishnevskiy/ElixirSublime#29]
I'm following the Phoenix guide (section: adding pages) and I'm getting this error as well. Phoenix version 1.1.4. The errors I'm getting are:

== Compilation error on file web/views/hello_view.ex ==
** (CompileError) web/views/hello_view.ex:2: module HelloPhoenix.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/views/hello_view.ex:2: HelloPhoenix.HelloView (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

and 

== Compilation error on file web/controllers/hello_controller.ex ==
** (CompileError) web/controllers/hello_controller.ex:2: module HelloPhoenix.Web is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    web/controllers/hello_controller.ex:2: HelloPhoenix.HelloController (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

ideas?

**Comment by divmgl** [comment]
@AndrewHendrie were you able to figure out what this is?

**Comment by LeAcid** [comment]
I am getting this same error, does anyone know why this won't work?

**Comment by AndrewHendrie** [comment]
lol totally my mistake. I named my application something other than "HelloPhoenix" ...so naturally the HelloPhoenix modules were not loaded. When I changed my view and controller code to MyApp.HelloController the code compiled without throwing any errors.
