### ISSUE TITLE
Default arguments screw up color scheme

### ISSUE THREAD

**Issue by hiporox** [vishnevskiy/ElixirSublime#37]
When using default arguments in Elixir 1.4 (i.e `def foo(n \\ 0)`), the color scheme following the function declaration become messed up. 

For example, I have this code:
```
def filter_url_domain(data, valid_domains \\ @valid_domains) do
    Logger.debug "Filtering out valid domains"
    data
```
Both the words `debug` and `data` show up in orange when they should be white. This error will continue for the rest of the file only effecting function calls and variable names, both of which should be white, but end up orange.

**Comment by binaryseed** [comment]
This project doesn't provide syntax highlighting.

A fix for this issue was just merged in the project that does:

https://github.com/elixir-lang/elixir-tmbundle/pull/122
