### ISSUE TITLE
Breaks shift+click for selection

### ISSUE THREAD

**Issue by pfac** [vishnevskiy/ElixirSublime#8]
Not sure even how to try and help with this, but installing this package disables the default selection behaviour of shift+click.

Using sublime text 3, build 3065.

**Comment by ylg** [comment]
Observed on ST 3083 as well, disabling ElixirSublime is the only "workaround" I've been able to find. Log output is:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "/Users/yurigadow/Library/Application Support/Sublime Text 3/Packages/ElixirSublime/elixir_sublime.py", line 218, in run
        if session.send('GOTO', selection):
      File "/Users/yurigadow/Library/Application Support/Sublime Text 3/Packages/ElixirSublime/elixir_sublime.py", line 189, in send
        self.socket.send(str.encode(cmd))
    AttributeError: 'NoneType' object has no attribute 'send'

**Comment by jamesmacaulay** [comment]
+1, this is frustrating. I use shift-click for selection all the time and couldn't figure out why it was broken until I tried uninstalling packages one by one. I think this plugin should merely provide the `"elixir_goto_definition"` command without forcing a particular shortcut, then tell people how to make their own keyboard shortcut to it in the README.

**Comment by YayConnolly** [comment]
+1, uninstalled for this reason :(

**Comment by onlydole** [comment]
+1, Uninstalled for the same reason...please fix this one!

**Comment by fnky** [comment]
+1 This has been a problem for me since I installed it back in December. I also vote for @jamesmacaulay's solution to this problem. It could conflict with other shortcuts, and I'd also like to pick my own shortcuts.

**Comment by fnky** [comment]
Actually I got this fixed by creating a `Default (OSX).sublime-mousemap`—where `(OSX)` would be `(Linux)` for Linux and `(Windows)` for Windows—in `<path to Sublime configuration>/Packages/User`.

You can find your Sublime configuration directory by going in `Preferences > Browse Packages...` and in the `User` directory.

```json
[
  {
    "button": "button1",
    "modifiers": ["alt"],
    "press_command": "drag_select",
    "command": "elixir_goto_definition"
  },
  {
    "button": "button1",
    "modifiers": ["shift"],
    "press_command": "drag_select",
    "press_args": {"extend": true}
  }
]
```

This will overwrite ElixirSublime's default mouse mapping configuration.

You can set the `modifiers` to anything you want. I chose `alt`. If you then hold your modifier key and click on a definition, it would go to the Elixir documentation for that definition.

**Comment by dsander** [comment]
@fnky Thank you! That works for me too.

**Comment by frantic** [comment]
+1

@vishnevskiy any plans to change `Shift+Click` to something that doesn't conflict with standard selection behavior? Or at least maybe there is a way to scope this only to Elixir source files?

**Comment by tomduncalf** [comment]
+1, thought I was going mad!

**Comment by murphyslaw** [comment]
:+1:

**Comment by matrinox** [comment]
:+1: Could not figure this out for the life of me. I thought I messed up some setting on my personal computer and I knew that would've been finding a needle in a haystack and I just couldn't be bothered. The google'ing was tough, I hope others find this easily. Shift+Click is so useful. I'm surprised they changed that behaviour, usually it's command+click or alt+click for function/method info

**Comment by rhapsodyv** [comment]
+1

**Comment by rustyfausak** [comment]
+1

**Comment by tompave** [comment]
+1
Issue still present with `Sublime Text 3 - build 3103`, and version `1.0.4` of the plugin.

**Comment by matrinox** [comment]
@tompave I have the exact same version for both and the issue's been fixed. I added a file named `ElixirSublime (User).sublime-mousemap` to: `~/Library/Application\ Support/Sublime\ Text 3/Packages/User` and added the above settings. Try that out

**Comment by nathany** [comment]
The worst part of this mousemap is it's not even scoped to Elixir, so it breaks shift-clicking for other languages too.

I'm just deleting ElixirSublime/Default (OSX).sublime-mousemap.

**Comment by adoyle-h** [comment]
+1

**Comment by thousandsofthem** [comment]
+1, uninstalled for this reason

**Comment by TimHeckel** [comment]
+1 @fnky - thank you

**Comment by TJKresch** [comment]
+1
Incredibly annoying. thanks @fnky

**Comment by xuanchien** [comment]
It does not work on my Sublime (build 3103). Any idea why? @fnky

**Comment by nighthawk** [comment]
+1. This is beyond frustrating. Also deleted `ElixirSublime/Default (OSX).sublime-mousemap`.

**Comment by joaquimadraz** [comment]
+1

**Comment by sergiotapia** [comment]
Still broken

**Comment by andfaulkner** [comment]
@fnky thank you so much, that was a huge help - that was driving me fucking crazy

**Comment by mcelaney** [comment]
+1

**Comment by lrascao** [comment]
+1

**Comment by hsmack** [comment]
+1

**Comment by konsti** [comment]
👍

**Comment by stephenkoo** [comment]
+1

**Comment by mwjaco** [comment]
+1

**Comment by lgdexter** [comment]
This was driving me mad. Thanks for pointing out this issue.

**Comment by laszlokorte** [comment]
+1

**Comment by fulgorek** [comment]
+1

**Comment by pragmaticivan** [comment]
+1

**Comment by Fire-Dragon-DoL** [comment]
Just faced the same problem, had to disable the package immediately.

**Comment by jelvin** [comment]
+1

on the same ⛵️

**Comment by jhammann** [comment]
+1

**Comment by bastianwegge** [comment]
+1

**Comment by hickscorp** [comment]
+1

**Comment by jaydorsey** [comment]
This appears to be fixed in issue #31 (June 2016). It doesn't look like a new version was pushed up to Package Control. A new release to Package Control should allow this to be closed

**Comment by okdas** [comment]
It took a while to figure out what was the problem. Why was the update not pushed though?

**Comment by jeffdeville** [comment]
@vishnevskiy Can you please push an updated version to package control to fix the mouse issue?

**Comment by Preen** [comment]
+1

**Comment by bitflorist** [comment]
+1

**Comment by rusterholz** [comment]
+1

**Comment by meowsus** [comment]
+1

**Comment by spnkr** [comment]
+1

**Comment by warnerandy** [comment]
+1

**Comment by mattisx** [comment]
Sigh.

**Comment by orzFly** [comment]
+1 annoyed me for almost one whole year

**Comment by fadhlirahim** [comment]
+1

**Comment by mcelaney** [comment]
I finally switched to https://github.com/elixir-editors/elixir-tmbundle which does anything I cared about from this package without the "Breaks shift+click for selection" bug.

**Comment by mezza** [comment]
+1

**Comment by DevL** [comment]
+1

**Comment by fuelxc** [comment]
Removed for this reason too

**Comment by netfull95** [comment]
+1

**Comment by zombiecong** [comment]
+1

**Comment by bitflorist** [comment]
I use vscode in the meantime ☺️

Von meinem iPhone gesendet

**Comment by divmgl** [comment]
This is still a problem almost four years since the creation of this issue

**Comment by pavellishin** [comment]
I finally got around to googling what was causing this, and just uninstalled it since I don't use Sublime for Elixir dev anymore :(

**Comment by vukanac** [comment]
Uninstalled. :(

**Comment by hscspring** [comment]
> Actually I got this fixed by creating a `Default (OSX).sublime-mousemap`—where `(OSX)` would be `(Linux)` for Linux and `(Windows)` for Windows—in `<path to Sublime configuration>/Packages/User`.
> 
> You can find your Sublime configuration directory by going in `Preferences > Browse Packages...` and in the `User` directory.
> 
> ```json
> [
>   {
>     "button": "button1",
>     "modifiers": ["alt"],
>     "press_command": "drag_select",
>     "command": "elixir_goto_definition"
>   },
>   {
>     "button": "button1",
>     "modifiers": ["shift"],
>     "press_command": "drag_select",
>     "press_args": {"extend": true}
>   }
> ]
> ```
> 
> This will overwrite ElixirSublime's default mouse mapping configuration.
> 
> You can set the `modifiers` to anything you want. I chose `alt`. If you then hold your modifier key and click on a definition, it would go to the Elixir documentation for that definition.

That's it, all about the Elixir, :)

**Comment by pfac** [comment]
Have not been using ElixirSublime for a long while, closing.
